name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - "4.14"
          - "5.4"

    runs-on: ubuntu-latest
    container: ghcr.io/formalsec/ocaml-${{ matrix.ocaml-compiler }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          opam update
          opam install -y . --deps-only --with-test

      - name: Build
        run: dune build @install

      - name: Test
        run: dune runtest
